name: youtube-uploader-dev

services:
  youtube-uploader:
    image: youtube-uploader:dev
    build: .

    ports:
      - "8080:8080"

    volumes:
      - ./.auth:/.auth

    # Obtain token.@channel.json from client_secret.json:
    #   docker compose run --rm -e PORT=4444 -p "4444:4444" youtube-uploader python oauth.py
