name: youtube-uploader-dev

services:
  youtube-uploader:
    image: youtube-uploader:dev
    build: .

    environment:
      MAX_VIDEO_BYTES: "1073741824" # 1 GiB

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - ./.auth:/.auth

    # Obtain token.@channel.json from client_secret.json:
    #   docker run --rm -it -e PORT=4444 -p "4444:4444" -v "./.auth:/.auth" youtube-uploader:dev oauth
