services:
  youtube-uploader:
    image: ghcr.io/tupinumboor/youtube-uploader

    environment:
      MAX_VIDEO_BYTES: "10737418240" # 10 GiB

    expose:
      - "8080"

    volumes:
      - ./.auth:/.auth

    # Obtain token.@channel.json from client_secret.json:
    #   docker compose run --rm -e PORT=4444 -p "4444:4444" youtube-uploader python oauth.py
